### ISSUE TITLE
wish: allow setting default options

### ISSUE THREAD

**Issue by markstos** [bevry/extract-opts#1]
Thanks for this module. It cleans up a common pattern in JavaScript.

I have a feature request: I'd like extractOpts() to take a third optional argument-- an object with default options. 

Currently I'm doing this:

``` javascript
     // Unpack args, allowing opts to be optional.
     var defaultOptions = { resultFormat : 'Point' };
     var args = extractOpts(opts,callback);
     opts = _.defaults(args[0],defaultOptions);
     callback = args[1];
```

It would be nicer to do this instead:

``` javascript
     var args = extractOpts(opts,callback,{ resultFormat : 'Point' });
     opts = _args[0];
     callback = args[1];
```

**Comment by balupton** [comment]
It's a fine idea, however considering the vast different ways of implementing default sets I'd find it hard to justify this being of reasonable scope or tact for this package, and rather best served as a local extension per-situation. Such as creating a util file that your local project uses that provides a wrapper around it that supports the default args, or perhaps releasing a new package around it.

**Comment by balupton** [comment]
this should be fairly to do via ESNext:

``` javascript
const {something = defaultValue} = extractOpts(opts, callback)
```
